services:
  - type: web
    name: rsy-whatsapp-sender-1
    env: node
    plan: free
    buildCommand: apt-get install -y chromium && npm install
    startCommand: node index.js
    envVars:
      - key: API_SECRET
        value: rsybattle_wa_2024
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
